<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RootNamespace>BTHaven.Probes.Common</RootNamespace>
    <AssemblyName>BTHaven.Probes.Common</AssemblyName>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
  </PropertyGroup>
</Project>
